[theme]
name = "neon"
desc = "Neon rice inspired by Stray"
version = "1.0"
author = "BeardWarrior"
git = "https://github.com/taylor85345/neon-hyprland-theme"
config = "theme.conf"

[kill]
exclude_bar = ["eww"]
exclude_wallpaper = ["swaybg,mpvpaper"]
